### ISSUE TITLE
Debug entry point

### ISSUE THREAD

**Issue by reppard** [manheim/vinbot#7]
https://github.com/manheim/vinbot/blob/master/bin/console#L7

We might want to remove this :smile:

**Comment by uchagani** [comment]
It's intentional so we can easily execute code at runtime and test various
things ;)

**Comment by reppard** [comment]
@uchagani ahh I gotcha.  I was just running some of our repos through code climate and rubocop freaked out :).  Back to our regularly scheduled program.
